// Code generated by Thrift Compiler (0.14.0). DO NOT EDIT.

package afas

import(
	"bytes"
	"context"
	"fmt"
	"time"
	"github.com/apache/thrift/lib/go/thrift"
	"immune/AttestationFailureAnalysisService/if/analyzerreport"
	"immune/AttestationFailureAnalysisService/if/caching_policy"
	"immune/AttestationFailureAnalysisService/if/measurements"
	"immune/AttestationFailureAnalysisService/if/tpm"
	"immune/AttestationFailureAnalysisService/pkg/analyzers/diffmeasuredboot/report/diffanalysis"
	"immune/AttestationFailureAnalysisService/pkg/analyzers/intelacm/report/intelacmanalysis"

)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal

var _ = analyzerreport.GoUnusedProtection__
var _ = caching_policy.GoUnusedProtection__
var _ = measurements.GoUnusedProtection__
var _ = tpm.GoUnusedProtection__
var _ = diffanalysis.GoUnusedProtection__
var _ = intelacmanalysis.GoUnusedProtection__

func init() {
}

