version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=afas
      - MYSQL_ROOT_PASSWORD=somePass
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./scripts/initdb:/docker-entrypoint-initdb.d
      - ./pkg:/pkg
  afasd:
    build:
      dockerfile: Dockerfile
      context: cmd/afasd
    environment:
      DBHOST: db
      DBUSER: root
      DBPASS: somePass
    ports:
      - 17545:17545
    volumes:
      - rootgo:/root/go
      - blobstore:/srv/afasd
      - ../attestation-sdk:/project
    links:
      - db
  orig-fw-repo:
    image: nginx
    volumes:
      - origfwimg:/srv/http
    ports:
      - 17546:17546
    command:
      - sh
      - -c
      - |
        cat > /etc/nginx/conf.d/default.conf <<EOF
        server {
          listen 17546;
          location / {
            autoindex on;
            root  /srv/http;
          }
        }
        EOF
        nginx -g 'daemon off;'
volumes:
  db:
    driver: local
  rootgo:
    driver: local
  blobstore:
    driver: local
  origfwimg:
    driver: local
