// Code generated by Thrift Compiler (0.14.0). DO NOT EDIT.

package pspsignanalysis

import(
	"bytes"
	"context"
	"fmt"
	"time"
	"github.com/apache/thrift/lib/go/thrift"
	"immune/AttestationFailureAnalysisService/pkg/analyzers/amd/types/psptypes"

)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal

var _ = psptypes.GoUnusedProtection__
const PSPSignatureAnalyzerID = "PSPSignature"

func init() {
}

