// Code generated by Thrift Compiler (0.14.0). DO NOT EDIT.

package analyzerreport

import(
	"bytes"
	"context"
	"fmt"
	"time"
	"github.com/apache/thrift/lib/go/thrift"
	"immune/AttestationFailureAnalysisService/pkg/analyzers/amd/apcbsectokens/report/apcbsecanalysis"
	"immune/AttestationFailureAnalysisService/pkg/analyzers/amd/biosrtmvolume/report/biosrtmanalysis"
	"immune/AttestationFailureAnalysisService/pkg/analyzers/amd/pspsignature/report/pspsignanalysis"
	"immune/AttestationFailureAnalysisService/pkg/analyzers/diffmeasuredboot/report/diffanalysis"
	"immune/AttestationFailureAnalysisService/pkg/analyzers/intelacm/report/intelacmanalysis"
	"immune/AttestationFailureAnalysisService/pkg/analyzers/reproducepcr/report/reproducepcranalysis"

)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal

var _ = apcbsecanalysis.GoUnusedProtection__
var _ = biosrtmanalysis.GoUnusedProtection__
var _ = pspsignanalysis.GoUnusedProtection__
var _ = diffanalysis.GoUnusedProtection__
var _ = intelacmanalysis.GoUnusedProtection__
var _ = reproducepcranalysis.GoUnusedProtection__

func init() {
}

