package models

import (
	"github.com/immune-gmbh/AttestationFailureAnalysisService/pkg/analysis"
)

// AnalyzerReport represents a report that was generated by a specific analyzer
type AnalyzerReport struct {
	ID              uint64              `db:"id"`
	AnalyzeReportID uint64              `db:"analyze_report_id"`
	AnalyzerID      analysis.AnalyzerID `db:"analyzer_id"` // TODO: remove this field from here, it should be just an index on the DB side
	Input           analysis.Input      `db:"input"`       // TODO: make typed, so that AnalyzeID could be removed
	Report          *analysis.Report    `db:"report"`
	ExecError       SQLErrorWrapper     `db:"exec_error"`
}
